#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch alacritty with bspwm config

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/alacritty/alacritty.toml"

if [ "$1" == "--float" ]; then
	alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG"
elif [ "$1" == "--full" ]; then
	alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' --config-file "$CONFIG" \
			  -o window.startup_mode="'Fullscreen'" \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
elif [ "$1" == "--rmatrix" ]; then
	alacritty --config-file "$CONFIG" -e $SHELL -c 'rmatrix -r && $SHELL' &
elif [ "$1" == "--neofetch" ]; then
	alacritty --config-file "$CONFIG" -e $SHELL -c 'neofetch && $SHELL' &
elif [ "$1" == "--pipes" ]; then
	alacritty --config-file "$CONFIG" -e $SHELL -c 'pipes && $SHELL' &
elif [ "$1" == "--music" ]; then
	alacritty --config-file "$CONFIG" -e ncmpcpp &
elif [ "$1" == "--cava" ]; then
	alacritty --config-file "$CONFIG" -e cava &
else
	alacritty --config-file "$CONFIG"
fi
