#!/usr/bin/env bash

## Copyright (C) 2020-2024 Fabrice Corraire <antidote1911@gmail.com>
##
## About Packarch

## Get ISO Version
if [[ -e '/version' ]]; then
	version="v`cat /version | cut -d'.' -f1`.`cat /version | cut -d '.' -f2`"
else
	version='rolling'
fi

yad --title='About Packarch' --window-icon='packarch-cyan' \
	--about \
	--pname='Packarch' \
	--pversion="$version" \
	--image='distributor-logo-packarch' \
	--comments="Yet another minimal linux distribution, Based on Arch Linux." \
	--copyright="Copyright 2020-`date +'%Y'`, Fabrice Corraire <antidote1911@gmail.com>" \
	--license='GPL3' \
	--website='https://github.com/packarch' \
	--website-label='packarch' \
	--authors="Fabrice Corraire <antidote1911@gmail.com>"
