#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst cairo-dock xfce4-power-manager

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Launch Polybar
bash ~/.config/openbox/themes/polybar.sh

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Launch Plank
exec cairo-dock &

## Thunar Daemon
exec thunar --daemon &
