#!/usr/bin/env zsh

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Openbox Pipemenu to open applications as root

# Variables and functions
MENUS_LIBDIR='/usr/share/packarch/openbox/menulib'
if ! . "$MENUS_LIBDIR/packarch.cfg" 2> /dev/null; then
	echo "Error: Failed to locate packarch.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

# cmd
root_cmd="$HOME/.config/openbox/scripts/ob-asroot"

# menu
menuStart
	menuItem 'Terminal' "$root_cmd 'alacritty'"
	menuItem 'Gestionnaire de fichiers' "$root_cmd 'dbus-run-session thunar'"
	menuItem 'Editeur de texte' "$root_cmd 'geany'"
	menuSeparator
	menuItem 'QT5 Settings' "$root_cmd 'qt5ct'"
	menuItem 'kvantum Manager' "$root_cmd 'kvantummanager'"
menuEnd
