#!/usr/bin/env bash

## Copyright (C) 2020-2021 Fabrice Corraire <antidote1911@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Openbox Pipemenu commands for web shortcuts

# Variables and functions
MENUS_LIBDIR='/usr/share/packarch/openbox/menulib'
if ! . "$MENUS_LIBDIR/packarch.cfg" 2> /dev/null; then
	echo "Error: Failed to locate packarch.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

menuStart
	menuItem 'Gmail' "firefox https://mail.google.com"
	menuItem 'Wiki Archlinux' "firefox https://wiki.archlinux.org/title/Main_page_(Fran%C3%A7ais)"
	menuItem 'Github Packarch' "firefox https://github.com/orgs/packarch/repositories"
	menuItem 'Youtube' "firefox https://www.youtube.com"
	menuItem '4Chan' "firefox https://www.4chan.org"
	
menuEnd

exit 0
